export const characters = [
  {
    id: 'diana',
    name: 'Diana P.',
    age: 302,
    location: 'Embassy Row, DC',
    tagline: 'Amazonian ambassador looking for honest mortals.',
    job: 'Museum curator & part-time demigoddess',
    bio: "Diplomat by day, unstoppable lasso-swinger by night. Seeking someone who respects boundaries, truth, and invisible jets. My friends say I take girlboss to 'Queen of Themyscira' levels.",
    redFlags: [
      'Keeps a golden lasso in the coat closet "for vibes"',
      'Will fact-check every white lie with alarming accuracy',
      'Commutes via invisible ride-share that you will never see',
    ],
    badges: ['Celestial Verified', 'Lasso of Truth Certified'],
    heroClass: 'hero-diana',
    avatarGradient: 'linear-gradient(135deg, #ff7ab8, #ffc46b)',
  },
  {
    id: 'clark',
    name: 'Clark K.',
    age: 34,
    location: 'Midtown, Metropolis',
    tagline: 'Mild-mannered reporter, definitely just that.',
    job: 'Investigative journalist & chronic bathroom break-taker',
    bio: 'My hobbies include catching deadlines, farm-to-table cooking (from an actual farm), and giving very good hugs. If we go out, please ignore if I vanish the moment the sky changes color.',
    redFlags: [
      'Glasses literally never come off',
      'Texts back at lightspeed then ghosts during crises',
      'All photos suspiciously taken in phone booth mirrors',
    ],
    badges: ['Solar Powered Verified', 'Pulitzer Pending'],
    heroClass: 'hero-clark',
    avatarGradient: 'linear-gradient(135deg, #45c4ff, #ff5d5d)',
  },
  {
    id: 'bruce',
    name: 'Bruce W.',
    age: 38,
    location: 'Gotham Heights Penthouse',
    tagline: 'Night owl billionaire seeking daylight companionship.',
    job: 'CEO & nocturnal enthusiast',
    bio: 'Introvert with a flair for dramatic entrances. Fluent in brooding, board meetings, and black capes. Looking for someone who appreciates cave aesthetics and whispered monologues.',
    redFlags: [
      'Butler manages his social media responses',
      'Never seen in public past sunset for unexplained reasons',
      'Owns more grappling hooks than dining chairs',
    ],
    badges: ['Forbes Billionaire', 'Brooding Certified'],
    heroClass: 'hero-bruce',
    avatarGradient: 'linear-gradient(135deg, #1b1b1f, #4b6cff)',
  },
  {
    id: 'peter',
    name: 'Peter P.',
    age: 23,
    location: 'Queens walk-up (top floor, obviously)',
    tagline: 'Science tutor with a sticky sense of humor.',
    job: 'Freelance photographer & neighborhood helper',
    bio: "Will absolutely introduce you to my aunt on date two. My camera roll is 90% skyline selfies from questionable angles. Looking for someone who doesn't mind the occasional web residue.",
    redFlags: [
      'Keeps spare clothes under every city bridge',
      'Will bail if GPS says “great responsibility” nearby',
      'Insists on hanging from ceiling during FaceTime',
    ],
    badges: ['Friendly Neighborhood Verified', 'Science Fair Champ'],
    heroClass: 'hero-peter',
    avatarGradient: 'linear-gradient(135deg, #ff4d6d, #ff9f1c)',
  },
  {
    id: 'thor',
    name: 'Thor O.',
    age: 1502,
    location: 'New Asgard coastal flat',
    tagline: 'Unemployed god with a hammer and feelings.',
    job: 'God of Thunder between gigs',
    bio: 'Currently on sabbatical from intergalactic heroics to work on myself and my storm-triggered emotions. Into craft beer, axes, and family therapy. Swipe right if you can lift me... emotionally.',
    redFlags: [
      'Brother shows up on every date with unsolicited advice',
      'Might bring a goat screaming playlist to set the mood',
      'Thunder follows me when I am even slightly hangry',
    ],
    badges: ['Celestial Verified', 'Realm Traveler'],
    heroClass: 'hero-thor',
    avatarGradient: 'linear-gradient(135deg, #8f5fff, #69f6ff)',
  },
  {
    id: 'natasha',
    name: 'Natasha R.',
    age: 35,
    location: 'Classified loft, Brooklyn',
    tagline: 'Reformed spy learning to overshare.',
    job: 'Consulting security strategist',
    bio: "Professional at reading people and still confused by dating app small talk. Therapy-going, trust-building, and learning that vulnerability isn't just a mission parameter.",
    redFlags: [
      'Has burner phones for her burner phones',
      'Knows your secrets before the first drink arrives',
      'All exes listed in a red ledger spreadsheet',
    ],
    badges: ['Background Check Approved', 'Therapy Overdrive'],
    heroClass: 'hero-natasha',
    avatarGradient: 'linear-gradient(135deg, #ff2e63, #c2f970)',
  },
  {
    id: 'tony',
    name: 'Tony S.',
    age: 45,
    location: 'Malibu smart house',
    tagline: 'Tech philanthropist. My AI pre-screened you.',
    job: 'CEO, inventor & sarcastic life coach',
    bio: "I build suits, satellites, and elaborate excuses to avoid sleep. Looking for someone who laughs at my jokes and doesn't mind the occasional world-saving push notification.",
    redFlags: [
      'AI assistant answers messages at 3 a.m.',
      'Sends calendar invites for cuddles',
      'Occasionally updates relationship status via press conference',
    ],
    badges: ['Forbes Billionaire', 'Genius Verified'],
    heroClass: 'hero-tony',
    avatarGradient: 'linear-gradient(135deg, #ff512f, #dd2476)',
  },
  {
    id: 'steve',
    name: 'Steve R.',
    age: 106,
    location: 'Brooklyn museum gift shop',
    tagline: 'Man out of time trying to swipe right on the future.',
    job: 'History consultant & reluctant influencer',
    bio: "Old-fashioned gentleman with modern-day confusion. I bring flowers, open doors, and still double-check slang on Urban Dictionary. Teach me TikTok and I'll teach you swing dancing.",
    redFlags: [
      'Still says “golly” unironically',
      'Carries a shield to brunch “just in case”',
      'Unfreezes emotionally at his own pace',
    ],
    badges: ['War Hero Verified', 'Time Traveler-ish'],
    heroClass: 'hero-steve',
    avatarGradient: 'linear-gradient(135deg, #4facfe, #00f2fe)',
  },
];
